//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wakency
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
       // public string fname { get; set; }
        //public string lname { get; set; }
        //public string email { get; set; }
        //public string contact { get; set; }
        //public string username { get; set; }
        //public string password { get; set; }
        //public string dept { get; set; }
        //public string year_of_study { get; set; }
        //public Nullable<System.DateTime> date_of_birth { get; set; }
        //public string company { get; set; }
        //public string profile { get; set; }
        //public string framework { get; set; }
        //public string languages { get; set; }
        //public string summary { get; set; }
        //public Nullable<System.DateTime> date_of_creation { get; set; }
    }
}
