//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wakency.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class job
    {
        public int job_id { get; set; }
        public string title { get; set; }
        public string company { get; set; }
        public string job_desc { get; set; }
        public string package { get; set; }
        public string posted_by { get; set; }
        public string attachment { get; set; }
        public string location { get; set; }
        public string job_type { get; set; }
        public string requirements { get; set; }
    }
}
