//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wakency.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        public int proj_id { get; set; }
        public string title { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> duration { get; set; }
        public string descr { get; set; }
        public string attachment { get; set; }
        public string req_languages { get; set; }
        public Nullable<int> posted_by { get; set; }
    }
}
